### ISSUE TITLE
Add module outputs

### ISSUE THREAD

**Issue by rgreinho** [innovationnorway/terraform-github-team#7]
If you are interested and want to create a `v1.x` branch like you did for the repository module, I have a patch to add `id` and `slug` outputs to this module.

**Comment by joakimhellum-in** [comment]
@rgreinho Sorry about the late reply. We created the [`v1.x`](https://github.com/innovationnorway/terraform-github-team/tree/v1.x) branch. Thanks alot for fixing this.

**Comment by rgreinho** [comment]
Fixed by #9
